# permissions for end users to view keystoneservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keystoneservice-viewer-role
rules:
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneservices/status
  verbs:
  - get
