# permissions for end users to view keystoneapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keystoneapi-viewer-role
rules:
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneapis/status
  verbs:
  - get
