# permissions for end users to edit keystoneapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keystoneapi-editor-role
rules:
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneapis/status
  verbs:
  - get
