# permissions for end users to edit keystoneendpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keystoneendpoint-editor-role
rules:
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneendpoints/status
  verbs:
  - get
