---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneapis/finalizers
  verbs:
  - update
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneapis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneservices/finalizers
  verbs:
  - update
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneservices/status
  verbs:
  - get
  - patch
  - update
