apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: keystoneapis.keystone.openstack.org
spec:
  group: keystone.openstack.org
  names:
    kind: KeystoneApi
    listKind: KeystoneApiList
    plural: keystoneapis
    singular: keystoneapi
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            adminDatabasePassword:
              description: Admin database password
              type: string
            adminPassword:
              description: Keystone API Admin Password
              type: string
            containerImage:
              description: Keystone Container Image URL
              type: string
            databaseHostname:
              description: Keystone Database Hostname String
              type: string
            databasePassword:
              description: Keystone Database Password String
              type: string
            mysqlContainerImage:
              description: Mysql Container Image URL (used for database syncing)
              type: string
            replicas:
              description: Replicas
              format: int32
              type: integer
          required:
          - replicas
          type: object
        status:
          properties:
            dbSyncVersion:
              description: Current Db sync version
              type: string
            messages:
              description: Deployment messages
              items:
                type: string
              type: array
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
