apiVersion: keystone.openstack.org/v1
kind: KeystoneService
metadata:
  name: example
spec:
  serviceName: example
  serviceType: example-type
  serviceDescription: >
    example description
  region: regionOne
  project: admin
  authURL: http://keystone-default.apps.ostest.test.metalkube.org
  username: admin
  password: foobar123
  domainName: Default
