kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keystone
subjects:
- kind: ServiceAccount
  name: keystone
roleRef:
  kind: Role
  name: keystone
  apiGroup: rbac.authorization.k8s.io
