apiVersion: keystone.openstack.org/v1beta1
kind: KeystoneService
metadata:
  name: placement
spec:
  serviceUser: placement
  enabled: true
  serviceDescription: "Placement service"
  serviceName: placement
  serviceType: placement
  secret: osp-secret
  passwordSelector: PlacementPassword
