apiVersion: keystone.openstack.org/v1beta1
kind: KeystoneAPI
metadata:
  name: keystoneapi-sample
spec:
  containerImage: docker.io/tripleotrain/centos-binary-keystone:current-tripleo
  replicas: 1
  databaseHostname: mariadb
  secret: keystone-secret
