## Append samples you want in your CSV to this file as resources ##
resources:
- keystone_v1beta1_keystoneapi.yaml
- keystone_v1beta1_keystoneservice.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
